# Setting "sudo" to false forces Travis-CI to use its
# container-based build infrastructure, which has shorter
# queue times.
sudo: false

# Use the newer Travis-CI build templates based on the
# Debian Linux distribution "Trusty" release.
dist: trusty

# Select Go as the language used to run the buid.
language: go
go: 1.8.3
go_import_path: github.com/thecodeteam/gocsi

jobs:
  include:

      # Verify GoCSI builds without errors
      - stage:   build
        env:     PROG=gocsi.a
        install: true
        script:  make $PROG

      - stage:   build
        env:     PROG=csc
        install: true
        script:  make -C $PROG

      - stage:   build
        env:     PROG=mock
        install: true
        script:  make -C $PROG

      # Test GoCSI's csp.sh script by creating and serving new SP and
      # then using csc to invoke GetSupportedVersions and GetPluginInfo
      - stage:   test
        env:     JOB=csi-sp
        install: make -C csc
        script:  make csi-sp

      # Test GoCSI using the Mock CSI plug-in.
      - stage:   test
        env:     JOB=test
        install: make ginkgo
        script:  make test

      # Benchmark GoCSI's PipeConn
      - stage:   test
        env:     JOB=bench
        install: true
        script:  make bench
